name: BoostedYAMLExample
version: '${project.version}'
main: dev.dejvokep.exampleboostedyamlplugin.BoostedYamlExample
api-version: 1.13
authors: [ dejvokep ]
description: An example Spigot plugin using the BoostedYAML library.
website: https://dejvokep.dev/
